src/Entity/Bordereau.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Bordereau
 *
 * @ORM\Table(name="bordereau")
 * @ORM\Entity(repositoryClass="App\Repository\BordereauRepository")
 */
class Bordereau
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateSaisie", type="datetime")
     */
    private $dateSaisie;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateExport", type="datetime", nullable=true)
     */
    private $dateExportProdon;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateExportCompta", type="datetime", nullable=true)
     */
    private $dateExportCompta;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateExportPlvt", type="datetime", nullable=true)
     */
    private $dateExportPlvt;

    /**
     * @var bool
     *
     * @ORM\Column(name="paiementPlvt", type="boolean", options={"default":false})
     */
    private $paiementPlvt;

    /**
     * @var int
     *
     * @ORM\Column(name="anneeCotis", type="integer")
     */
    private $anneeCotis;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Section", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * @Assert\Valid()
     */
    private $section;

    /**
     * @var Transactions[]
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="bordereau", cascade={"persist"}, fetch="EAGER")
     *
     * @Assert\Valid()
     */
    private $transactions;

    /**
     * @var bool
     *
     * @ORM\Column(name="validated", type="boolean", options={"default":false})
     */
    private $validated;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateSaisie
     *
     * @param \DateTime $dateSaisie
     *
     * @return Bordereau
     */
    public function setDateSaisie($dateSaisie)
    {
        $this->dateSaisie = $dateSaisie;

        return $this;
    }

    /**
     * Get dateSaisie
     *
     * @return \DateTime
     */
    public function getDateSaisie()
    {
        return $this->dateSaisie;
    }

    /**
     * Set anneeCotis
     *
     * @param integer $anneeCotis
     *
     * @return Bordereau
     */
    public function setAnneeCotis($anneeCotis)
    {
        $this->anneeCotis = $anneeCotis;

        return $this;
    }

    /**
     * Get anneeCotis
     *
     * @return int
     */
    public function getAnneeCotis()
    {
        return $this->anneeCotis;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->transactions = new \Doctrine\Common\Collections\ArrayCollection();
        $this->setDateSaisie(new \DateTime());
        $this->validated = false;
    }

    /**
     * Add transaction
     *
     * @param \App\Entity\Transaction $transaction
     *
     * @return Bordereau
     */
    public function addTransaction(\App\Entity\Transaction $transaction)
    {
        $this->transactions[] = $transaction;

        return $this;
    }

    /**
     * Remove transaction
     *
     * @param \App\Entity\Transaction $transaction
     */
    public function removeTransaction(\App\Entity\Transaction $transaction)
    {
        $this->transactions->removeElement($transaction);
    }

    /**
     * Get transactions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Set section
     *
     * @param \App\Entity\Section $section
     *
     * @return Bordereau
     */
    public function setSection(\App\Entity\Section $section)
    {
        $this->section = $section;

        return $this;
    }

    /**
     * Get section
     *
     * @return \App\Entity\Section
     */
    public function getSection()
    {
        return $this->section;
    }

    /**
     * Set validated
     *
     * @param boolean $validated
     *
     * @return Bordereau
     */
    public function setValidated($validated)
    {
        $this->validated = $validated;

        return $this;
    }

    /**
     * Get validated
     *
     * @return boolean
     */
    public function getValidated()
    {
        return $this->validated;
    }

    /**
     * Set dateExportProdon
     *
     * @param \DateTime $dateExportProdon
     *
     * @return Bordereau
     */
    public function setDateExport($dateExportProdon)
    {
        $this->dateExportProdon = $dateExportProdon;

        return $this;
    }

    /**
     * Get dateExportProdon
     *
     * @return \DateTime
     */
    public function getDateExportProdon()
    {
        return $this->dateExportProdon;
    }

    /**
     * Set dateExportProdon
     *
     * @param \DateTime $dateExportProdon
     *
     * @return Bordereau
     */
    public function setDateExportProdon($dateExportProdon)
    {
        $this->dateExportProdon = $dateExportProdon;

        return $this;
    }

    /**
     * Set dateExportCompta
     *
     * @param \DateTime $dateExportCompta
     *
     * @return Bordereau
     */
    public function setDateExportCompta($dateExportCompta)
    {
        $this->dateExportCompta = $dateExportCompta;

        return $this;
    }

    /**
     * Get dateExportCompta
     *
     * @return \DateTime
     */
    public function getDateExportCompta()
    {
        return $this->dateExportCompta;
    }

    public function getDateExportPlvt(): ?\DateTimeInterface
    {
        return $this->dateExportPlvt;
    }

    public function setDateExportPlvt(?\DateTimeInterface $dateExportPlvt): self
    {
        $this->dateExportPlvt = $dateExportPlvt;

        return $this;
    }

    public function getPaiementPlvt(): ?bool
    {
        return $this->paiementPlvt;
    }

    public function setPaiementPlvt(bool $paiementPlvt): self
    {
        $this->paiementPlvt = $paiementPlvt;

        return $this;
    }
}

src/Entity/Transaction.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator as CustomAssert;

/**
 * Transaction
 *
 * @ORM\Table(name="transaction")
 * @ORM\Entity(repositoryClass="App\Repository\TransactionRepository")
 *
 * @CustomAssert\VerifCotisation()
 */
class Transaction
{
    const TARIF_HL = 20;
    const TARIF_LDHINFO = 10;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var float
     *
     * @ORM\Column(name="cotisation", type="float", nullable=true)
     * @Assert\Range(
     *     min = 10,
     *     minMessage="La cotisation ne peut être inférieure à {{ limit }} €."
     * )
     */
    private $cotisation;

    /**
     * @var integer
     *
     * @ORM\Column(name="hl", type="integer", nullable=true)
     */
    private $hl = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="ldh_info", type="integer", nullable=true)
     */
    private $ldhInfo = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="don_siege", type="float", nullable=true)
     */
    private $donSiege;

    /**
     * @var float
     *
     * @ORM\Column(name="don_section", type="float", nullable=true)
     */
    private $donSection;

    /**
     * @var float
     *
     * @ORM\Column(name="total", type="float", nullable=true)
     */
    private $total;

    /**
     * @var Bordereau
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Bordereau", inversedBy="transactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bordereau;

    /**
     * @var Adherent
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Adherent", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * @Assert\Valid()
     */
    private $adherent;

    /**
     * @var string
     *
     * @ORM\Column(name="note", type="string", length=255, nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="date")
     */
    private $paiementDate;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $paiementType;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $paiementRef;

    public function __construct()
    {

    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set bordereau
     *
     * @param \App\Entity\Bordereau $bordereau
     *
     * @return Transaction
     */
    public function setBordereau(\App\Entity\Bordereau $bordereau)
    {
        $this->bordereau = $bordereau;

        return $this;
    }

    /**
     * Get bordereau
     *
     * @return \App\Entity\Bordereau
     */
    public function getBordereau()
    {
        return $this->bordereau;
    }

    /**
     * Set adherent
     *
     * @param \App\Entity\Adherent $adherent
     *
     * @return Transaction
     */
    public function setAdherent(\App\Entity\Adherent $adherent)
    {
        $this->adherent = $adherent;

        return $this;
    }

    /**
     * Get adherent
     *
     * @return \App\Entity\Adherent
     */
    public function getAdherent()
    {
        return $this->adherent;
    }

    /**
     * Set cotisation
     *
     * @param float $cotisation
     *
     * @return Transaction
     */
    public function setCotisation($cotisation)
    {
        $this->cotisation = $cotisation;

        return $this;
    }

    /**
     * Get total
     *
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Set total
     *
     * @param float $total
     *
     * @return Transaction
     */
    public function setTotal($total)
    {
        $this->total = $total;

        return $this;
    }

    /**
     * Get cotisation
     *
     * @return float
     */
    public function getCotisation()
    {
        return $this->cotisation;
    }

    /**
     * Set hl
     *
     * @param integer $hl
     *
     * @return Transaction
     */
    public function setHl($hl)
    {
        $this->hl = $hl;

        return $this;
    }

    /**
     * @return bool
     */
    public function getHlSubscription()
    {
        return (bool) $this->hl;
    }

    /**
     * @param bool $bool
     */
    public function setHlSubscription($bool)
    {
        $this->hl = $bool ? self::TARIF_HL : 0;
    }

    /**
     * @return bool
     */
    public function getLdhInfoSubscription()
    {
        return (bool) $this->ldhInfo;
    }

    /**
     * @param bool $bool
     */
    public function setLdhInfoSubscription($bool)
    {
        $this->ldhInfo = $bool ? self::TARIF_LDHINFO : 0;
    }

    /**
     * Get hl
     *
     * @return integer
     */
    public function getHl()
    {
        return $this->hl;
    }

    /**
     * Set ldhInfo
     *
     * @param integer $ldhInfo
     *
     * @return Transaction
     */
    public function setLdhInfo($ldhInfo)
    {
        $this->ldhInfo = $ldhInfo;

        return $this;
    }

    /**
     * Get ldhInfo
     *
     * @return integer
     */
    public function getLdhInfo()
    {
        return $this->ldhInfo;
    }

    /**
     * Set donSiege
     *
     * @param float $donSiege
     *
     * @return Transaction
     */
    public function setDonSiege($donSiege)
    {
        $this->donSiege = $donSiege;

        return $this;
    }

    /**
     * Get donSiege
     *
     * @return float
     */
    public function getDonSiege()
    {
        return $this->donSiege;
    }

    /**
     * Set donSection
     *
     * @param float $donSection
     *
     * @return Transaction
     */
    public function setDonSection($donSection)
    {
        $this->donSection = $donSection;

        return $this;
    }

    /**
     * Get donSection
     *
     * @return float
     */
    public function getDonSection()
    {
        return $this->donSection;
    }

    /**
     * Set note
     *
     * @param string $note
     *
     * @return Transaction
     */
    public function setNote($note)
    {
        $this->note = $note;

        return $this;
    }

    /**
     * Get note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    public function getPaiementDate(): ?\DateTimeInterface
    {
        return $this->paiementDate;
    }

    public function setPaiementDate(\DateTimeInterface $paiementDate): self
    {
        $this->paiementDate = $paiementDate;

        return $this;
    }

    public function getPaiementType(): ?string
    {
        return $this->paiementType;
    }

    public function setPaiementType(string $paiementType): self
    {
        $this->paiementType = $paiementType;

        return $this;
    }

    public function getPaiementRef(): ?string
    {
        return $this->paiementRef;
    }

    public function setPaiementRef(?string $paiementRef): self
    {
        $this->paiementRef = $paiementRef;

        return $this;
    }


}

src/Form/BordereauType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class BordereauType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('anneeCotis', ChoiceType::class, array(
                'choices' => array(
                    date("Y") => date("Y"),
                    date("Y") - 1 => date("Y") - 1,
                    date("Y") + 1 => date("Y") + 1,
                ),
                'label' => 'Année de cotisation',
            ))
            ->add('paiementPlvt', CheckboxType::class, array(
            'label' => "Je choisis que la part siège de ce bordereau soit prélevée sur le compte bancaire de la section, en lieu et place de l'envoi d'un chèque",
            //'value' => Transaction::TARIF_HL,
            'required' => false,
            ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Bordereau'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_bordereau';
    }


}

templates/bordereau/_formTransaction.html.twig
<div class="mb-4 alert alert-warning mandatory">Champs obligatoires.</div>

{{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate':'', 'autocomplete':'off'}}) }}

{# Les erreurs générales du formulaire. #}
{{ form_errors(form) }}
<div class="bg-light rounded p-3 mb-3">
    <h4>Identification</h4>
    <div class="form-row">
        <div class="form-group col-md-3">
            {# Génération du label. #}
            {{ form_label(form.adherent.noAdh, "N° d'adhérent") }}
            {# Génération de l'input. #}
            {{ form_widget(form.adherent.noAdh, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.adherent.noAdh) }}
            <div class="invalid-tooltip">Veuillez respecter le format</div>
            <small class="form-text text-muted">Ne saisir que des chiffres, sans espace, sans les éventuels 0 qui précèdent (005 834 devient
                5834).<br>
                <strong>En saisissant le n° d'adhérent (si c'est un renouvellement), cela limite le risque de création de doublon et
                    vous n'avez pas besoin de resaisir toutes les coordonnées de l'adhérent (sauf le sexe, nom et prénom -champs suivis de *-).</strong>
            </small>

        </div>
        <div class="form-group col-md-3">
            {{ form_label(form.adherent.dateNaissance, "Date de naissance") }}
            {{ form_widget(form.adherent.dateNaissance) }}
            {{ form_errors(form.adherent.dateNaissance) }}
        </div>
        <div class="form-group col-md-6">
            {{ form_label(form.adherent.profession, "Profession ou ancienne profession") }}
            {{ form_widget(form.adherent.profession) }}
            {{ form_errors(form.adherent.profession) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group required col-md-3">
            {{ form_label(form.adherent.civilite, "Sexe") }}
            {{ form_widget(form.adherent.civilite) }}
            <div class="invalid-tooltip">Le sexe est obligatoire</div>
            {{ form_errors(form.adherent.civilite) }}

        </div>
        <div class="form-group required col-md-5">
            {{ form_label(form.adherent.nom, "Nom") }}
            {{ form_widget(form.adherent.nom) }}
            <div class="invalid-tooltip">Le nom est obligatoire</div>
            {{ form_errors(form.adherent.nom) }}
        </div>
        <div class="form-group required col-md-4">
            {{ form_label(form.adherent.prenom, "Prénom") }}
            {{ form_widget(form.adherent.prenom) }}
            <div class="invalid-tooltip">Le prénom est obligatoire</div>
            {{ form_errors(form.adherent.prenom) }}
        </div>
    </div>
</div>
<div class="bg-light rounded p-3 mb-3">
    <h4>Coordonnées</h4>
    <small class="form-text text-muted"><strong>Ne remplissez le cadre coordonnées que si :</strong>
        <ul>
            <li>Certaines informations ont changé (adresse postale ou téléphone ou adresse email). Remplissez alors uniquement ce qui a changé.</li>
            <li>Il s'agît d'un nouvel adhérent.</li>
            <li>Vous n'avez pas saisi le numéro d'adhérent plus haut.</li>
        </ul>
    </small>
    <div class="form-group">
        {{ form_label(form.adherent.adresse, "Adresse") }}
        {{ form_widget(form.adherent.adresse, {'attr': {'rows': '4', 'data-toggle': 'tooltip', 'data-placement': 'left', 'title': 'Ne saisissez l\'adresse, le code postal et la ville que ci ceux-ci ont changé ou si vous n\'avez pas indiqué de n° d\'adhérent plus haut.'}}) }}
        {{ form_errors(form.adherent.adresse) }}
        <small class="form-text text-muted">Si changement - sur 4 lignes maximum</small>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2">
            {{ form_label(form.adherent.codePostal, "Code Postal") }}
            {{ form_widget(form.adherent.codePostal) }}
            {{ form_errors(form.adherent.codePostal) }}
            <small class="form-text text-muted">Si changement</small>
        </div>
        <div class="form-group col-md-10">
            {{ form_label(form.adherent.ville, "Ville") }}
            {{ form_widget(form.adherent.ville) }}
            {{ form_errors(form.adherent.ville) }}
            <small class="form-text text-muted">Si changement</small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            {{ form_label(form.adherent.telephone, "Téléphone") }}
            {{ form_widget(form.adherent.telephone, {'attr': {'data-toggle': 'tooltip', 'data-placement': 'left', 'title': 'Ne saisir que si changement'}}) }}
            {{ form_errors(form.adherent.telephone) }}
        </div>
        <div class="form-group col-md-6">
            {{ form_label(form.adherent.email, "Email") }}
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <div class="input-group-text">@</div>
                </div>
                {{ form_widget(form.adherent.email, {'attr': {'data-toggle': 'tooltip', 'data-placement': 'left', 'title': 'Ne saisir que si changement'}}) }}
                {{ form_errors(form.adherent.email) }}
            </div>
            <small class="form-text text-muted">Pour recevoir sa carte et son reçu fiscal par email, et s'inscrire aux
                listes de diffusion
            </small>
        </div>
    </div>
</div>
{# Partie transaction #}
<div class="bg-light rounded p-3 mb-3">
    <h4>Paiement</h4>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{ form_label(form.cotisation, "Cotisation") }}
            {{ form_widget(form.cotisation) }}
            <div class="invalid-tooltip">La cotisation minimum est de 10 €</div>
            {{ form_errors(form.cotisation) }}
        </div>
        <div class="form-group col-md-4">
            {{ form_label(form.donSiege, "Don pour le siège") }}
            {{ form_widget(form.donSiege) }}
            {{ form_errors(form.donSiege) }}
        </div>
        <div class="form-group col-md-4">
            {{ form_label(form.donSection, "Don pour la section") }}
            {{ form_widget(form.donSection) }}
            {{ form_errors(form.donSection) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{ form_label(form.hlSubscription, "Abonnements") }}
            {{ form_widget(form.hlSubscription) }}
            {{ form_errors(form.hlSubscription) }}
        </div>
        <div class="form-group col-md-4">
            {{ form_label(form.ldhInfoSubscription, "Abonnements") }}
            {{ form_widget(form.ldhInfoSubscription) }}
            {{ form_errors(form.ldhInfoSubscription) }}
            <small class="form-text text-muted">Version numérique gratuite par email (dans ce cas ne pas cocher, l'adhérent recevra sa carte de membre par email et un lien lui permettra de s'inscrire).</small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group required col-md-3">
            {{ form_label(form.paiementDate, "Date du paiement (format JJ/MM/AAAA)") }}
            {{ form_widget(form.paiementDate) }}
            <div class="invalid-tooltip">La date du paiement est obligatoire</div>
            {{ form_errors(form.paiementDate) }}
            <small class="form-text text-muted">Doit correspondre à la date du paiement. Pour un chèque, c'est la date figurant sur le chèque.
                Cette date est prise en compte pour l'année du reçu fiscal.</small>
        </div>
        <div class="form-group col-md-2">
            {{ form_label(form.paiementType, "Moyen de paiement") }}
            {{ form_widget(form.paiementType) }}
            <div class="invalid-tooltip">Le moyen de paiement est obligatoire</div>
            {{ form_errors(form.paiementType) }}
        </div>
        <div class="form-group col-md-3">
            {{ form_label(form.paiementRef, "N° du chèque (si paiement en chèque)") }}
            {{ form_widget(form.paiementRef) }}
            {{ form_errors(form.paiementRef) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            {{ form_label(form.total, "Total payé par l'adhérent") }}
            {{ form_widget(form.total, {'attr': {'data-toggle': 'tooltip', 'data-placement': 'left', 'title': 'Champ calculé automatiquement'}}) }}
            {{ form_errors(form.total) }}
        </div>
    </div>
</div>
<div class="form-group mt-4">
    {{ form_label(form.note, "Notes ou remarques") }}
    {{ form_widget(form.note) }}
    {{ form_errors(form.note) }}
    <small class="form-text text-muted">Commentaires éventuels à remonter au siège sur cette adhésion (nouveau,
        changement d'adresse, de situation...)
    </small>
</div>
<div class="form-row mt-4">
    <div class="form-group col-md-6">
        <input type="submit" value="{{ bouton }}"
               class="btn btn-primary"/>
    </div>
</div>

{{ form_rest(form) }}
        {{ form_end(form) }}

templates/bordereau/createBordereau.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Créer un bordereau - Etape 1{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Création d'un bordereau de reversement pour la section {{ app.user.nom }}</h4>
                    {% if form is defined %}
                        {{ form_start(form) }}
                        {{ form_widget(form) }}

                        {% if not app.user.rum %}
                            <div class="alert alert-success">Si c'est la première fois que vous choisissez de payer la part siège par prélèvement bancaire, vous devez remplir un mandat de prélèvement
                                téléchargeable <a href="https://partage.ldh-france.org/s/gPtfJiAgo2PTkrA/download" target="_blank">au format PDF en cliquant ici</a> ou <a href="https://partage.ldh-france.org/s/E95nyz5oBBbLjwm/download" target="_blank">au format Word en cliquant là</a>.<br> Il vous faudra le remplir avec les informations bancaires (RIB) de la section soit :<br>
                            <ul>
                                <li>IBAN : {{ app.user.iban }}</li>
                                <li>BIC : {{ app.user.bic }}</li>
                            </ul>
                                Vous pouvez le retourner signé, par email à <a href="mailto:laboutique@ldh-france.org">laboutique@ldh-france.org</a> ou par courrier postal, il vous permettra également d'être prélevé pour vos factures de la boutique.<br>
                            Avec ce choix, vous n'avez plus besoin d'envoyer de chèque et vous économisez un timbre !</div>
                        {% endif %}

                        <input type="submit" value="Ajouter des personnes"
                               class="btn btn-primary mt-4" />
                        {{ form_end(form) }}
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/bordereau/editTransaction.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Créer un bordereau - Etape 2{% endblock %}

{% block body %}
    {% if form is defined %}
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Modifier une ligne (adhérent)</h4>
                        {% include 'bordereau/_formTransaction.html.twig' with {'bouton': 'Enregistrer la modification'} %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/add_transaction.js') }}"></script>
{% endblock %}

templates/bordereau/sendBordereau.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Bordereau transmis{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Bordereau transmis au siège</h4>
                    {% if bordereau is defined %}
                        <div><p>Le bordereau a bien été envoyé !</p>
                            {% if not bordereau.paiementPlvt %}
                                <p>Vous pouvez régler la part du siège avec un chèque de <strong>{{ bordereau|partSiege }} €</strong> en portant au dos la référence du bordereau : <strong>B-{{ bordereau.section.compteComptable }}-{{ bordereau.id }}</strong></p>
                            {% else %}
                                <p>Votre bordereau porte la référence <strong>B-{{ bordereau.section.compteComptable }}-{{ bordereau.id }}</strong>.<br>
                                N'envoyez pas de chèque, le compte bancaire de la section sera prélevé de <strong>{{ bordereau|partSiege }} €</strong> dans quelques jours.</p>
                            {% endif %}
                        </div>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}